server:
  error:
    include-message: always
    include-binding-errors: always

DB_DRIVER_CLASS: ${DB_DRIVER_CLASS}
DB_BASE_URL: ${DB_BASE_URL}
DB_USER: ${DB_USER}
DB_PASSWORD: ${DB_PASSWORD}
DB_DDL_AUTO: ${DB_DDL_AUTO}
DB_DIALECT: ${DB_DIALECT}

spring:    
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  secret: myVeryLongAndSecureSecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmSecurity
  expiration: 86400000
